# Generated by Django 5.2.7 on 2025-11-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='сourse',
            new_name='course',
        ),
    ]
