# Generated by Django 5.2.7 on 2025-11-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lessonquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonquantity',
            name='course',
        ),
    ]
