# Generated by Django 5.2.7 on 2025-11-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
