# Generated by Django 5.2.7 on 2025-11-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
